# Site settings
title: mrich316.github.io
#email: 
description: >
  Martin Richard works at city of Laval. His job is to challenge status quo,
  propose new ideas and shake the virtual landscape of his natal city.
baseurl: ""
url: "https://mrich316.github.io"
author:
  name: Martin Richard
  #twitter_username: mrich316
  github_username: mrich316
  linkedin_baseurl: https://ca.linkedin.com/in/
  linkedin_username: mrich316
  

# Build settings
markdown: kramdown
